### ISSUE TITLE
An error occurred when I use Llama3-8B-Instruct to Retrieval Needle In A HayStack

### ISSUE THREAD

**Issue by lwj2001** [HKUNLP/ChunkLlama#22]
src code is that:
`
    generation_output = model.generate(
        input_ids=input_ids, max_new_tokens=answer_ids.shape[-1], num_beams=1, use_cache=use_cache
    )
`
when set `max_new_tokens=answer_ids.shape[-1]` (In my case, this value is 1), prediction is null, but set its value to 2, pediction is the first three digits of a six-digit number,such as 123 in 123456. Now i set its value to 3, and prediction is the whole number. 
Why does this situation arise?

**Comment by ChenxinAn-fdu** [comment]
Interesting question! This issue is caused by Llama3 generating an extra space first, while Llama2 does not.

```
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False, trust_remote_code=True)
prompt = str(123456)
answer_ids = tokenizer(prompt, return_tensors="pt").input_ids[:, 1:]  
# answer_ids => [ 4513, 10961]
print(tokenizer.decode([4513]))
>>> 123
print(tokenizer.decode([10961]))
>>> 456
```
during generation, the model will first generate an extra space. So if we set `max_new_tokens = 1`, the generation results will be a space ` ` (token_id=220).  When we set `max_new_tokens = 2`, the results will be `[220, 4513]`=" 123".
 When we set `max_new_tokens = 3`, the results will be correct.

However, in my case, 123456 will be tokenized into 2 ids. If you get `answer_ids.shape[-1]=1` I think the number is likely to be contained in the vocab of Llama3. 

Please feel free to leave a comment if you are still confused about it.

**Comment by lwj2001** [comment]
Thanks reply! I just learned that Llama3 will first generate an extra space :). But in my case, 123456 also will be tokenized into 2 ids. And get `answer_ids.shape[-1]=2`
```
answer_ids = tokenizer(prompt, return_tensors="pt").input_ids[:, 1:]  
# answer_ids => [10961]
```
confused about that：
why we not set `answer_ids = tokenizer(prompt, return_tensors="pt").input_ids` 
while set `answer_ids = tokenizer(prompt, return_tensors="pt").input_ids[:, 1:]`

**Comment by ChenxinAn-fdu** [comment]
This is used to delete the special bos token `<|begin_of_text|>`.

**Comment by lwj2001** [comment]
I know. Thank you and i will close issue.
